### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus20/kevinwe-chess#1]
Well done this week Kevin!

However, when I try to run `cargo test`, I'm met with:
```
error: aborting due to 24 previous errors; 1 warning emitted
```

Your errors seems to be in relation to invalid function calls to `position_check`. Let me explain. 
```rust
pub fn position_check(self, _rank: i8, _file: i8) -> Option<Piece>
```
`position_check` takes `self` as an immutable argument, making the function a member of an instance of `Game`. Therefore, to call `position_check`, you have to go through an instance of `Game` like so:
```rust
self.position_check(/*...*/);
```

To get a pass, make your engine compilable by fixing those 24 errors.

**Comment by azraneth** [comment]
What you saw there was me panicking over not allocating enough tine for the project. I had a compilable version of those functions but they were in the wrong scope, and in my haste to fix it I left the changes somewhat uncompleted. It does compile now though!
